### ISSUE TITLE
Please avoid importing from @mui/material directly.

### ISSUE THREAD

**Issue by ha-ku** [the-maazu/react-material-music-player#14]
Please avoid importing from `@mui/material` directly in components like this:
```
import { Box, SwipeableDrawer, Paper } from "@mui/material";
```
This may result in something like `var _material = require("@mui/material")` which requires the whole mui package during compiling and thus significantly slows down the building progress, especially on machines with small ram size.

An alternative solution is simply using path imports:
```
import Box from "@mui/material/Box";
import SwipeableDrawer from "@mui/material/SwipeableDrawer";
...
```

**Comment by the-maazu** [comment]
Thanks for bringing this to my attention. I specifically chose this to make code readable and assuming tree shaking bundlers are used, end products at the browser should be minified.

To improve build time for library users I think the best thing to do will be to employ babel-plugin-import without making changes to the code base.

Will push this as soon as possible.

**Comment by ha-ku** [comment]
I also just noticed this myself several hours ago. Because I've never write a library, my suggestion may also not be proper enough. Hope you don't mind it. Looking forwards to the update soon!
