### ISSUE TITLE
Warning: Received NaN for the `value` attribute. If this is expected, cast the value to a string.

### ISSUE THREAD

**Issue by tptspe** [the-maazu/react-material-music-player#17]
Hi Guys.
First of all, I'd like to say thanks for this package.
It works fine with MUI 5.x.
Btw, I am getting some warnings and I want some features with this.

Here are my warning in my browser console.
- `Warning: Received NaN for the `value` attribute. If this is expected, cast the value to a `string.``
- `Warning: Failed prop type: The prop `value` is marked as required in `ForwardRef(ToggleButton)`, but its value is `undefined`.`
- `Warning: Failed prop type: The prop `classes` is marked as required in `PlaylistItemTemplate`, but its value is `undefined``

Here are my feature list what I want.
- display or hide audio list
- active or inactive auto playing
- switch mini or standard mode
- any option to set the player position(currently its position is bottom by default)

Expected Behavior:
1. I'd like to resolve and remove above warnings.
2. I'd like to get the access to control above 3 cases what I want.

My Environment is
- Windows 10 pro
- Vs code editor
- @mui/icons-material: "5.6.1"
- @mui/material: "5.6.1"
- @mui/system: "5.6.1"
- react-material-music-player": "^1.1.2",
- "next": "12.1.5",
- "react": "^18.0.0",
- "react-dom": "^18.0.0"

Hope your good feedback soon!
Thanks.

**Comment by the-maazu** [comment]
> * `Warning: Received NaN for the `value`attribute. If this is expected, cast the value to a`string.``
> * `Warning: Failed prop type: The prop `value`is marked as required in`ForwardRef(ToggleButton)`, but its value is `undefined`.`
> * `Warning: Failed prop type: The prop `classes`is marked as required in`PlaylistItemTemplate`, but its value is `undefined``
Can you take a screen shot or a full stack trace so we can see where the warning is coming from.

> * display or hide audio list
I am not sure what exactly you mean by this.

> * active or inactive auto playing
I suggest you add this to discussion section, preferrably under "ideas".

> * switch mini or standard mode
> * any option to set the player position(currently its position is bottom by default)
You can do these two things like below:
<code>&lt;Player sx={{position: "static", width: "100px", height: "20px"}} disableDrawer={true}&gt;</code>
Note if the <em>width</em> and <em>height</em> is small enough it will automatically enter "mini mode"

**Comment by tptspe** [comment]
@the-maazu 
Thanks for your reply.
Here are my answers for your questions.
- Screenshots in my console for the above warnings
![image](https://user-images.githubusercontent.com/26249890/165237691-8c925794-0242-42ec-b238-fcae5299d453.png)
![image](https://user-images.githubusercontent.com/26249890/165237723-fa0eeb01-8838-49cd-9ce8-224096c09a0c.png)
- display or hide audio list
I meant the option to display or hide audio list icon.
Because if I provide the only one track, then it doesn't need to display at all.
![image](https://user-images.githubusercontent.com/26249890/165238055-46d93093-1f1c-4815-879a-8ec306644ba9.png)
- active or inactive auto playing
Okay, I will post new issue with `ideas`
- switch mini or standard mode, any option to set the player position(currently its position is bottom by default)
For the player position, I solved it myself with sx props.
For mini mode, I wanted this mini mode style from here.
https://werter12.github.io/material-ui-audio-player/?path=/story/material-ui--small-audioplayer

Actually, I wanted this style, but it doesn't support mui 5.x unfortunately.

Thanks

**Comment by the-maazu** [comment]
> * display or hide audio list
>   I meant the option to display or hide audio list icon.
>   Because if I provide the only one track, then it doesn't need to display at all.
>   ![image](https://user-images.githubusercontent.com/26249890/165238055-46d93093-1f1c-4815-879a-8ec306644ba9.png)

Yes I can see what you are sayiing. We can hide playlist controls when only one track is loaded. Kindly move this to "idea".

> * switch mini or standard mode, any option to set the player position(currently its position is bottom by default)
>   For the player position, I solved it myself with sx props.
>   For mini mode, I wanted this mini mode style from here.
>   https://werter12.github.io/material-ui-audio-player/?path=/story/material-ui--small-audioplayer

For a similar mini mode you can reduce size using <em>sx</em> props but only cover art will be visible. It is a good idea to overlay a play/pause button on the cover art when in mini mode. Kindly move this one too to "idea".

> Actually, I wanted [material-ui-audio-player](https://www.npmjs.com/package/material-ui-audio-player), but it doesn't support mui 5.x unfortunately. If you can update to get the similar options and props like that, it would be great.

Yes you can do alot of styling via the <em>sx</em> props and even take adavantage of the theming solution by targeting MUI components(Box, Buttons etc) within the player. Take a look at [makeTheme.js](https://github.com/the-maazu/react-material-music-player/tree/main/src).

Will add more music control via the interface in javascript.

**Comment by tptspe** [comment]
@the-maazu Thanks for your kindly reply.
When can I get your updating with above ideas, especially `mini mode`?
Can you let me know once you updated new version?
