### ISSUE TITLE
Error: Invalid hook call

### ISSUE THREAD

**Issue by jefmsmit** [the-maazu/react-material-music-player#25]
I'm trying to use the `<Player/>` component inside of a function component and I keep getting an invalid hook call error. 
I know with 100% certainty that my component that is using the `<Player/>` component is in the body of a function component as I am using other hooks successfully. Just to be sure, I even tried wrapping the `<Player/>` inside another function component like this:

```
const ArchiveAudioPlayer = (props:{tracks: Track[]}) => {
  return (
    <Player/>
  )
}
```

Same issue. 

I know my react and react-dom versions match as this problem only started happening with this component. 

Any ideas?

**Comment by the-maazu** [comment]
which version of react are you using?

**Comment by jefmsmit** [comment]
Using version 18.

**Comment by the-maazu** [comment]
upgrade the package to version 1.1.5

**Comment by the-maazu** [comment]
let me know if this solved the problem sp i can close the issue
