### ISSUE TITLE
Keep alive in iOS?

### ISSUE THREAD

**Issue by daggmano** [the-maazu/react-material-music-player#28]
I'm not sure if this is a limitation of any web-based player, but I've noticed, on my iPhone, that while this player continues the current track until the end, it does not then continue to the next track. It would be great to be able to set up a playlist to play while the phone is locked. Is this possible?

**Comment by the-maazu** [comment]
I have made some prelimnary observations and it seems to be a descrapancy in how HTMLAudioElement handles a change in "src" property. For iOS Safari it seems we have to explicitly instruct it to continue playing once there is a change, which is not the case with desktop browsers or android browser. Will work on this soon.

**Comment by the-maazu** [comment]
It seems Javascript execution is suspended when Safari is in the background on iOS. As I do not have an iphone its quite difficult to debug this.

Interesting to note this discussion https://discussions.apple.com/thread/2298038, by adding the web app to the homescreen iOS seems to give more privilege and allow javascript to continue execution. But this is old and might not be the current behaviour.
