### ISSUE TITLE
Doesn't work in webview 

### ISSUE THREAD

**Issue by viis233** [the-maazu/react-material-music-player#29]
in react native webview at android .
following errors will occur.
<img width="617" alt="图片" src="https://user-images.githubusercontent.com/41282272/182015569-c2c0f976-b060-495e-a0c3-4e7d6946f040.png">

**Comment by the-maazu** [comment]
Yes MediaSession, is currently not supported by android webview. Will have to explicitly check for MediaSession support before applying the middleware.

For now what you can do is to fork the project and comment out the mediaSessionActions in [middleware](https://github.com/the-maazu/react-material-music-player/blob/main/src/module/redux/store.js).

<code>&gt yarn prepublishOnly</code>

Then copy the "dist" folder to your project src. You can rename "dist" to your liking. Replace all "react-material-music-player" imports with path to renamed "dist" folder.

Let me know if you need more help.

**Comment by the-maazu** [comment]
You can now upgrade package to 1.1.9 for mediaSession support check. But note without mediaSession support users cannot control playback from the system UI (notification tray).
