### ISSUE TITLE
How do  i fix it? it happens when i queue more than 10 songs

### ISSUE THREAD

**Issue by Babypluto192** [the-maazu/react-material-music-player#39]
![image](https://github.com/the-maazu/react-material-music-player/assets/68411079/59848fa8-79bc-4393-abe4-451bfe809038)

**Comment by Babypluto192** [comment]
NVM i fixed trough looking at css classes

**Comment by the-maazu** [comment]
Thanks, was hoping you'd make a pull request...fixed now.
